"""add audit logs

Revision ID: 0ce910188602
Revises: 967e95c12306
Create Date: 2026-07-02 09:17:09.749486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ce910188602'
down_revision: Union[str, Sequence[str], None] = '967e95c12306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('incident_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('idx_audit_event', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_audit_incident', 'audit_logs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_incident_id'), 'audit_logs', ['incident_id'], unique=False)
    op.drop_index(op.f('idx_comment_author'), table_name='comments')
    op.drop_index(op.f('idx_comment_incident'), table_name='comments')
    op.drop_index(op.f('ix_comments_incident_id'), table_name='comments')
    op.drop_table('comments')
    op.alter_column('incident_comments', 'incident_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('incident_comments', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('incident_comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incident_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incident_comments', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('incident_comments', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('incident_comments', 'incident_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('comments',
    sa.Column('incident_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('author_role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('comment_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_edited', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('edit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ai_sentiment_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_incident_id'), 'comments', ['incident_id'], unique=False)
    op.create_index(op.f('idx_comment_incident'), 'comments', ['incident_id'], unique=False)
    op.create_index(op.f('idx_comment_author'), 'comments', ['author_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_incident_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index('idx_audit_incident', table_name='audit_logs')
    op.drop_index('idx_audit_event', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
