"""add_history_attachment_comment_tables

Revision ID: 967e95c12306
Revises: 2025db562419
Create Date: 2026-06-23 05:59:36.861754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967e95c12306'
down_revision: Union[str, Sequence[str], None] = '2025db562419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=128), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by_role', sa.String(length=100), nullable=True),
    sa.Column('virus_scan_status', sa.String(length=50), nullable=False),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('classification_label', sa.String(length=100), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index('idx_attachment_hash', 'attachments', ['sha256_hash'], unique=False)
    op.create_index('idx_attachment_incident', 'attachments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_attachments_incident_id'), 'attachments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_attachments_sha256_hash'), 'attachments', ['sha256_hash'], unique=False)
    op.create_table('comments',
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.Column('author_role', sa.String(length=100), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=100), nullable=True),
    sa.Column('ai_sentiment_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_author', 'comments', ['author_id'], unique=False)
    op.create_index('idx_comment_incident', 'comments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_comments_incident_id'), 'comments', ['incident_id'], unique=False)
    op.add_column('incident_history', sa.Column('event_type', sa.String(length=100), nullable=False))
    op.add_column('incident_history', sa.Column('field_name', sa.String(length=100), nullable=True))
    op.add_column('incident_history', sa.Column('change_reason', sa.Text(), nullable=True))
    op.add_column('incident_history', sa.Column('performer_role', sa.String(length=100), nullable=True))
    op.add_column('incident_history', sa.Column('source_system', sa.String(length=100), nullable=False))
    op.add_column('incident_history', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.add_column('incident_history', sa.Column('ip_address', sa.String(length=100), nullable=True))
    op.add_column('incident_history', sa.Column('workflow_state_before', sa.String(length=100), nullable=True))
    op.add_column('incident_history', sa.Column('workflow_state_after', sa.String(length=100), nullable=True))
    op.add_column('incident_history', sa.Column('risk_score_before', sa.Integer(), nullable=True))
    op.add_column('incident_history', sa.Column('risk_score_after', sa.Integer(), nullable=True))
    op.add_column('incident_history', sa.Column('is_system_generated', sa.Boolean(), nullable=False))
    op.create_index('idx_history_actor', 'incident_history', ['performed_by'], unique=False)
    op.create_index('idx_history_incident_event', 'incident_history', ['incident_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_incident_history_event_type'), 'incident_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_incident_history_performed_by'), 'incident_history', ['performed_by'], unique=False)
    op.drop_column('incident_history', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_history', sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_incident_history_performed_by'), table_name='incident_history')
    op.drop_index(op.f('ix_incident_history_event_type'), table_name='incident_history')
    op.drop_index('idx_history_incident_event', table_name='incident_history')
    op.drop_index('idx_history_actor', table_name='incident_history')
    op.drop_column('incident_history', 'is_system_generated')
    op.drop_column('incident_history', 'risk_score_after')
    op.drop_column('incident_history', 'risk_score_before')
    op.drop_column('incident_history', 'workflow_state_after')
    op.drop_column('incident_history', 'workflow_state_before')
    op.drop_column('incident_history', 'ip_address')
    op.drop_column('incident_history', 'session_id')
    op.drop_column('incident_history', 'source_system')
    op.drop_column('incident_history', 'performer_role')
    op.drop_column('incident_history', 'change_reason')
    op.drop_column('incident_history', 'field_name')
    op.drop_column('incident_history', 'event_type')
    op.drop_index(op.f('ix_comments_incident_id'), table_name='comments')
    op.drop_index('idx_comment_incident', table_name='comments')
    op.drop_index('idx_comment_author', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_attachments_sha256_hash'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_incident_id'), table_name='attachments')
    op.drop_index('idx_attachment_incident', table_name='attachments')
    op.drop_index('idx_attachment_hash', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
