from enum import Enum


class IncidentEventType(str, Enum):

    INCIDENT_CREATED = "INCIDENT_CREATED"

    STATUS_CHANGED = "STATUS_CHANGED"

    COMMENT_ADDED = "COMMENT_ADDED"

    TECHNICIAN_ASSIGNED = "TECHNICIAN_ASSIGNED"

    ATTACHMENT_ADDED = "ATTACHMENT_ADDED"

    PRIORITY_CHANGED = "PRIORITY_CHANGED"

    INCIDENT_ESCALATED = "INCIDENT_ESCALATED"

    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"

    INCIDENT_CLOSED = "INCIDENT_CLOSED"

    RISK_RECALCULATED = "RISK_RECALCULATED"

    SLA_STARTED = "SLA_STARTED"

    SLA_BREACHED = "SLA_BREACHED"

    SLA_RECOVERED = "SLA_RECOVERED"
